# This is a basic workflow to help you get started with Actions
name: On Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  deployment_status:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  print-info:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo 'hi'
    
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
